-- MySQL Script generated by MySQL Workbench
-- Qua 29 Nov 2017 00:58:03 -02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pain_o_matic
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pain_o_matic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pain_o_matic` DEFAULT CHARACTER SET utf8 ;
USE `pain_o_matic` ;

-- -----------------------------------------------------
-- Table `pain_o_matic`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pain_o_matic`.`user` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(30) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pain_o_matic`.`doctor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pain_o_matic`.`doctor` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(90) NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_doctor_user_idx` (`user_id` ASC),
  CONSTRAINT `fk_doctor_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `pain_o_matic`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pain_o_matic`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pain_o_matic`.`patient` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(90) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `rg` VARCHAR(18) NOT NULL,
  `photo` VARCHAR(90) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pain_o_matic`.`appointment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pain_o_matic`.`appointment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `patient_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_appointment_patient1_idx` (`patient_id` ASC),
  CONSTRAINT `fk_appointment_patient1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `pain_o_matic`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pain_o_matic`.`diagram`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pain_o_matic`.`diagram` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(125) NOT NULL,
  `img_diagram_depth1` VARCHAR(90) NULL DEFAULT 'diagram-model.png',
  `img_diagram_depth2` VARCHAR(90) NULL DEFAULT 'diagram-model.png',
  `img_diagram_depth3` VARCHAR(90) NULL DEFAULT 'diagram-model.png',
  `img_diagram_depth4` VARCHAR(90) NULL DEFAULT 'diagram-model.png',
  `appointment_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_diagram_appointment1_idx` (`appointment_id` ASC),
  CONSTRAINT `fk_diagram_appointment1`
    FOREIGN KEY (`appointment_id`)
    REFERENCES `pain_o_matic`.`appointment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pain_o_matic`.`nursingHistoric`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pain_o_matic`.`nursingHistoric` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `questions` JSON NOT NULL,
  `patient_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `patient_id`),
  INDEX `fk_historicoEnfermagem_patient1_idx` (`patient_id` ASC),
  CONSTRAINT `fk_historicoEnfermagem_patient1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `pain_o_matic`.`patient` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
